#!/bin/bash

####################################################################################################
#                                                                                                  #
#  CC-BY-NC-4.0 License v4.0                                                                       #
#                                                                                                  #
#  Copyright (c) 2026 Roberto Chichiarelli "Robic"                                                 #
#  Created by Roberto Chichiarelli                                                                 #
#  GitHub: https://github.com/Rob1c                                                                #
#  Development period: July 2025 -                                                                 #
#                                                                                                  #
#  Any violation of the license terms may result                                                   #
#  in termination of rights granted under this license.                                            #
#                                                                                                  #
#  For commercial licensing inquiries, contact: roberto.chichiarelli@gmail.com                     #
#                                                                                                  #
####################################################################################################

set -e

INSTALL_DIR="/opt/ghidra"
EXEC="$INSTALL_DIR/ghidraRun"
SYMLINK="/usr/bin/ghidra"

chmod +x "$EXEC"

if [ ! -L "$SYMLINK" ]; then
    ln -sf "$EXEC" "$SYMLINK"
fi

if command -v update-desktop-database >/dev/null; then
    update-desktop-database /usr/share/applications
fi

if command -v gtk-update-icon-cache >/dev/null && [ -d /usr/share/icons/hicolor ]; then
    gtk-update-icon-cache -q /usr/share/icons/hicolor
fi

exit 0
