name: Build Ghidra Debian Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# in view of the NodeJS 20 deprecation...
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Debian Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts debhelper dpkg-dev lintian fakeroot rsync

      - name: Fetch Latest Ghidra Release Data
        id: ghidra_api
        run: |
          JSON=$(curl -s https://api.github.com/repos/NationalSecurityAgency/ghidra/releases/latest)
          DOWNLOAD_URL=$(echo "$JSON" | jq -r '.assets[] | select(.name | endswith(".zip")) | .browser_download_url')
          VERSION_TAG=$(echo "$JSON" | jq -r '.tag_name' | sed 's/Ghidra_//;s/_build//')

          echo "url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT
          echo "version=$VERSION_TAG" >> $GITHUB_OUTPUT

      - name: Download Ghidra
        run: wget ${{ steps.ghidra_api.outputs.url }} -O ghidra.zip

      - name: Prepare Workspace
        run: |
          mkdir -p package/debian
          mkdir -p package/opt/ghidra
          mkdir -p package/usr/bin
          mkdir -p package/usr/share/applications
          mkdir -p package/usr/share/pixmaps

          unzip ghidra.zip -d temp_ghidra
          mv temp_ghidra/*/* package/opt/ghidra/

          cp debian/control debian/postinst debian/postrm package/debian/
          cp usr/share/applications/ghidra.desktop package/usr/share/applications/
          cp usr/share/icons/hicolor/scalable/apps/uno-ghidra.svg package/usr/share/icons/hicolor/scalable/apps/

      - name: Inject Version into Control
        run: |
          sed -i "s/Version:.*/Version: ${{ steps.ghidra_api.outputs.version }}/" package/debian/control

      - name: Finalize Permissions
        run: |
          chmod 755 package/debian/postinst package/debian/postrm
          chmod -R 755 package/opt/ghidra
          chmod -R 755 package/usr

      - name: Build Official Debian Package (debuild)
        run: |
          cd build_env/${{ github.event.repository.name }}-${UPSTREAM_VERSION}
          debuild -us -uc

      - name: Create Clean Source Code Archives (Zip & Tar.gz)
        run: |
          git archive --format=zip --output=${{ github.event.repository.name }}_${UPSTREAM_VERSION}_source.zip HEAD
          git archive --format=tar.gz --output=${{ github.event.repository.name }}_${UPSTREAM_VERSION}_source.tar.gz HEAD

      - name: Upload All Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ env.DEB_VERSION }}
          path: |
            build_env/*.deb
            build_env/*.changes
            build_env/*.buildinfo
            *_source.zip
            *_source.tar.gz
